### ISSUE TITLE
Fix error in checkbashisms-linter

### ISSUE THREAD

**Issue by jakob-fritz** [jakob-fritz/github2lab_action#16]
Maybe use a fixed docker-image with checkbashisms preinstalled.

Use
``` YAML
runs-on: ubuntu-latest
    container: node:10.16-jessie
    steps:
      - run: |
```
to define a container-image
